### ISSUE TITLE
[BUG] Moonraker install cannot enable wled.py

### ISSUE THREAD

**Issue by lokiagent** [Guilouz/Creality-K1-and-K1-Max#341]
### What happened?

When enabling a [wled] section in moonraker.conf, moonraker attempts to update the required python packages and fails to install pyserial-asyncio 0.6, so shuts off the wled component.

### What did you expect to happen instead?

Load and update all packages needed to start wled

### How to reproduce this issue?

Fresh install, add [wled anything] to moonraker.conf and restart moonraker.

### Additional information:

Debug section:
`2024-01-29 21:17:24,121 [server.py:try_pip_recovery()] - Module 'serial_asyncio' not found. Attempting Pip Update...
2024-01-29 21:17:24,121 [server.py:try_pip_recovery()] - Checking Pip Version...
2024-01-29 21:17:34,155 [server.py:try_pip_recovery()] - Pip version check failed
Traceback (most recent call last):
  File "/usr/data/moonraker/moonraker/moonraker/server.py", line 284, in load_component
    module = importlib.import_module(full_name)
  File "/usr/data/moonraker/moonraker-env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 749, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/data/moonraker/moonraker/moonraker/components/wled.py", line 15, in <module>
    import serial_asyncio
ModuleNotFoundError: No module named 'serial_asyncio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/data/moonraker/moonraker/moonraker/server.py", line 321, in try_pip_recovery
    pipver = pip_exec.get_pip_version()
  File "/usr/data/moonraker/moonraker/moonraker/utils/pip_utils.py", line 122, in get_pip_version
    resp = self.call_pip_with_response("--version", 10.)
  File "/usr/data/moonraker/moonraker/moonraker/utils/pip_utils.py", line 111, in call_pip_with_response
    return _run_subprocess_with_response(f"{self.pip_cmd} {args}", timeout, env)
  File "/usr/data/moonraker/moonraker/moonraker/utils/pip_utils.py", line 44, in _run_subprocess_with_response
    proc = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 491, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1024, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1867, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/usr/lib/python3.8/subprocess.py", line 1068, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['/usr/data/moonraker/moonraker-env/bin/python', '-m', 'pip', '--version']' timed out after 10.0 seconds
2024-01-29 21:17:34,156 [server.py:load_component()] - Unable to load component: (wled)
Traceback (most recent call last):
  File "/usr/data/moonraker/moonraker/moonraker/server.py", line 284, in load_component
    module = importlib.import_module(full_name)
  File "/usr/data/moonraker/moonraker-env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 749, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/data/moonraker/moonraker/moonraker/components/wled.py", line 15, in <module>
    import serial_asyncio
ModuleNotFoundError: No module named 'serial_asyncio'`

Manual install of serial_asyncio with `python3 -m pip install pyserial-asyncio==0.6` repairs the issue and allows wled component to activate.

**Comment by Guilouz** [comment]
Will be added to my next script version with Moonraker installer.
